.TH Manhattan 8 "June 15 2016" "Version 1.0"
.SH NAME
    Manhattan - A tool for generating Seccomp configurations
.SH SYNOPSIS
    manhattan [OPTION] [ARGUMENT]...[OPTION] [ARGUMENT]...
.SH DESCRIPTION
    A command line tool for creating JSON configurations that can be used by
    any OCI standard compliant platform.
.SH AUTHOR
    Grant Seltzer, <gseltzer@redhat.com>
.SH USAGE
    Arguments consist of all lower case names of syscalls. Multiple ones can be
    passed by using a , separated list. Use any of the following flags to set
    actions for specified syscalls:

    --input, -i
        Specifies location of base configuration file

    --kill, -k
        Set kill action for specified syscall(s)

    --trap
        Set trap action for specified syscall(s)

    --errno, -e
        Set errno action for specified syscall(s)

    --trace
        Set trace action for specified syscall(s)

    --allow, -a
        Set allow action for specified syscall(s)

    FOR SETTING SPECIFIC ARGUMENTS:

        manhattan [ACTION] [SYSCALL]:[INDEX]:[VALUE1]:[VALUE2]:[OP]

        OP can be any of the following: NE, LT, LE, EQ, GE, GT, ME

    --remove, -r
        Specifies syscalls that you would like to remove from default config

    --default, -d
        Specifies the default action for syscalls not explicitly specified

    --architecture, --arch
        Specifies support architectures

    --name, -n
        Specifies the name of the output file.

.SH EXAMPLES
    manhattan --kill accept --name ~/jsonfiles/SeccompConfig

    manhattan --kill=accept , manhattan --kill:accept and manattan --kill accept are all equivalent

    manhattan --errno write,read --allow fstat

    manhattan --default kill --remove clone

    manhattan --trace clone:1:2:3:GT

    manhattan --arch mips,mips64,amd64
